export const LOCALIZATION_SET_LOADING = 'LOCALIZATION_SET_LOADING'
export const LOCALIZATION_SET_LANGUAGE = 'LOCALIZATION_SET_LANGUAGE'
export const LOCALIZATION_SET_LANGUAGE_REQUESTED =
  'LOCALIZATION_SET_LANGUAGE_REQUESTED'
